// @vitest-environment jsdom
import { describe, expect, it } from "vitest";
import { buildSelector } from "./selector";
import { loadPlayground, pointableElements, type PlaygroundPage } from "./test-utils/playground";

/** Anything generated by a framework or a utility-CSS tool: none may reach a selector (plan step 7). */
const NOISE = [
  /data-v-/, /_ngcontent/, /_nghost/, /:r\d+:/, /radix-/, /css-1a2b3c/, /sc-bdVaJa/, /kUgNyR/,
  /3xKz1/, /a8Kd2/, /Mui[^"]*-outlined/,
  /\.(flex|inline-flex|border|rounded|sr-only|mx-auto)\b/, /\.(p|px|py|mt|gap|h|w)-\d/,
  /\.(bg|text|font|tracking|divide|min-w|max-w|items|justify|grid-cols|hover)[-:]/,
];

function expectUniqueAndClean(doc: Document): void {
  const elements = pointableElements(doc);
  expect(elements.length).toBeGreaterThan(10);
  for (const el of elements) {
    const { selector, unique } = buildSelector(el);
    const context = `${el.outerHTML.slice(0, 80)} → ${selector}`;
    expect(unique, context).toBe(true);
    expect(Array.from(doc.querySelectorAll(selector)), context).toEqual([el]);
    for (const pattern of NOISE) expect(selector, context).not.toMatch(pattern);
  }
}

describe("buildSelector on the playground", () => {
  it.each<PlaygroundPage>(["index.html", "other.html"])("gives every element of %s a unique, noise-free selector", (page) => {
    expectUniqueAndClean(loadPlayground(page).window.document);
  });

  it.each(["?view=/dashboard", "?view=/reports"])("covers the SPA view %s", (suffix) => {
    const dom = loadPlayground("spa.html", { runScripts: true, suffix });
    expect(dom.window.document.querySelector("#view h1")).not.toBeNull();
    expectUniqueAndClean(dom.window.document);
    dom.window.close();
  });

  it("prefers stable tokens in D3 order", () => {
    const doc = loadPlayground("index.html").window.document;
    const pick = (css: string) => buildSelector(doc.querySelector(css) as Element).selector;
    expect(pick("#export-btn")).toBe("#export-btn");
    expect(pick('[aria-label="More actions"]')).toBe('button[aria-label="More actions"]');
    expect(pick('a[href="other.html"]')).toBe('a[href="other.html"]');
    expect(pick('[data-source="src/components/Toolbar.tsx:8"]')).toBe('[data-source="src/components/Toolbar.tsx:8"]');
    expect(pick(".private-note")).toBe("div.private-note");
    expect(pick("#settings-form button")).toBe("#settings-form > button.primary");
  });
});

describe("buildSelector rules", () => {
  function fixture(html: string): Document {
    document.body.innerHTML = html;
    return document;
  }

  it("uses data-testid before an id", () => {
    const doc = fixture('<button id="save" data-testid="save-button">Save</button>');
    expect(buildSelector(doc.querySelector("button") as Element).selector).toBe('[data-testid="save-button"]');
  });

  it("anchors CSS-module classes by their stable prefix, never the hash", () => {
    const doc = fixture(
      '<div><button class="Toolbar_export__3xKz1">A</button><button class="Toolbar_print__9Qw2e">B</button></div>',
    );
    expect(buildSelector(doc.querySelector(".Toolbar_export__3xKz1") as Element).selector).toBe(
      'button[class*="Toolbar_export__"]',
    );
  });

  it("skips generated ids and falls back to nth-of-type", () => {
    const doc = fixture('<ul><li id=":r7:">a</li><li id="mui-123">b</li><li id="3f2b8c1e-8a9d-4c1e-9f0a-1b2c3d4e5f60">c</li></ul>');
    const items = Array.from(doc.querySelectorAll("li"));
    expect(items.map((li) => buildSelector(li).selector)).toEqual([
      "li:nth-of-type(1)", "li:nth-of-type(2)", "li:nth-of-type(3)",
    ]);
  });

  it("escapes identifiers and quotes attribute values", () => {
    const doc = fixture('<button id="a.b">x</button><input name=\'say "hi"\'>');
    const button = doc.querySelector("button") as Element;
    const input = doc.querySelector("input") as Element;
    expect(buildSelector(button)).toEqual({ selector: "#a\\.b", unique: true });
    expect(buildSelector(input)).toEqual({ selector: 'input[name="say \\"hi\\""]', unique: true });
  });

  // PRIVACY ATTACK (D8): aria-label is a normal D3 candidate token, but when the *labelled
  // element itself* is sensitive its aria-label often mirrors the value (masked-value
  // accessible names). candidateTokens used to read it unconditionally, so the selector kept
  // for a sensitive field could carry its own secret value.
  it("never puts a sensitive element's aria-label value into the selector", () => {
    const doc = fixture('<input type="password" aria-label="CANARY-7391">');
    expect(buildSelector(doc.querySelector("input") as Element).selector).not.toContain("CANARY-7391");
  });

  it("skips aria-label for an element inside a data-sensitive ancestor too", () => {
    const doc = fixture('<div data-sensitive><span aria-label="CANARY-7391">x</span></div>');
    expect(buildSelector(doc.querySelector("span") as Element).selector).not.toContain("CANARY-7391");
  });

  it("still uses aria-label for a non-sensitive element (no over-redaction)", () => {
    const doc = fixture('<button aria-label="More actions">⋯</button>');
    expect(buildSelector(doc.querySelector("button") as Element).selector).toBe('button[aria-label="More actions"]');
  });

  it("reports unique: false when the depth cap is reached before the selector is unique", () => {
    const doc = fixture("<div><div><span>a</span></div></div><div><div><span>b</span></div></div>");
    const span = doc.querySelectorAll("span")[1] as Element;
    expect(buildSelector(span, { maxDepth: 2 })).toEqual({ selector: "div > span", unique: false });
    expect(buildSelector(span)).toEqual({ selector: "div:nth-of-type(2) > div > span", unique: true });
  });
});

describe("buildSelector privacy", () => {
  it("never puts an href that redactUrl would change into the selector", () => {
    document.body.innerHTML =
      '<nav><a class="cb" href="/callback#access_token=CANARY-7391">x</a><a class="cb" href="/other">y</a></nav>';
    const { selector, unique } = buildSelector(document.querySelector("a.cb") as Element);
    expect(selector).not.toContain("CANARY");
    expect(unique).toBe(true);
  });
});
